"""Relationship fix

Revision ID: 7d2171b1d2f0
Revises: 8fb76f9086ad
Create Date: 2026-01-06 15:43:04.427128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2171b1d2f0'
down_revision: Union[str, Sequence[str], None] = '8fb76f9086ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('order_item', sa.Column('prod_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'product', ['prod_id'], ['id'])
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'prod_id')
    op.drop_column('order_item', 'order_id')
    # ### end Alembic commands ###
